
version: 2.1

# You can replace your executor in any job with an executor defined here. A good start would be replacing the image in your Docker executor with one of our convience images.
# The Docker executor meets the needs of over 80% of our users.
# https://circleci.com/docs/2.0/executor-types
executors:
  default:
    docker:
  # List of convenience images: https://circleci.com/docs/2.0/circleci-images/#latest-image-tags-by-language
      - image: circleci/python
    working_directory: ~/proj
  macos:
    macos:
      xcode: "10.1.0"
    working_directory: ~/proj
    shell: /bin/bash --login
  windows:
    machine:
      resource_class: windows.medium
      image: "windows-server-2019:201908-06"
      shell: bash
  
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
              - build

jobs:
  build:
    executor: docker
    steps:
      - sh "./run-build.sh"
  deploy:
    executor: docker
    steps:
      - sh "./run-deploy.sh"
