
version: 2.1

# You can replace your executor in any job with an executor defined here. A good start would be replacing the image in your Docker executor with one of our convience images.
# The Docker executor meets the needs of over 80% of our users.
# https://circleci.com/docs/2.0/executor-types
executors:
  default:
    docker:
  # List of convenience images: https://circleci.com/docs/2.0/circleci-images/#latest-image-tags-by-language
      - image: circleci/python:3.6
    working_directory: ~/proj
  macos:
    macos:
      xcode: "10.1.0"
    working_directory: ~/proj
    shell: /bin/bash --login
  windows:
    machine:
      resource_class: windows.medium
      image: "windows-server-2019:201908-06"
      shell: bash
  
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - foo

jobs:
  foo:
    executor: default
    steps:
      - run: echo "hello"
      - run: sh "test -f Jenkinsfile"


# triggers are supported in CircleCI, however we strongly recommend you achieve your
#  first green build before implementing this feature.
# Please refer to https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow for more information.
#  triggers {
#  cron('@daily')
#  }

# options do not have a direct correlation to CircleCI syntax
# Please refer to https://circleci.com/docs/2.0/configuration-reference/#workflows for more information.
#  options {
#  buildDiscarder(logRotator(numToKeepStr:'1'))
#  disableConcurrentBuilds()
#  skipDefaultCheckout(true)
#  timeout(time: 5, unit: 'MINUTES')
#  timestamps()
#  }

