version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.8.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: create artifacts dir
          command: mkdir -p ~/project/artifacts          
      - run:
          name: create config.yml
          command: ~/project/test/createConfigs.sh
      - store_artifacts:
          path: ~/project/artifacts
      - persist_to_workspace:
          root: ~/project
          paths:
            - artifacts/
            - test/validateConfigs.sh

  test:
    docker:
      - image: circleci/node:12.8.0
    working_directory: ~/project
    steps:
      - run:
          name: install CircleCI CLI
          command: curl -fLSs https://circle.ci/cli | sudo bash
      - attach_workspace:
          at: ~/project
      - run:
          name: validate configs
          command: ~/project/test/validateConfigs.sh

workflows:
  version: 2
  btd:
    jobs:
      - build
      - test:
          requires:
            - build

