version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.8.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: create artifacts dir
          command: mkdir -p ~/artifacts          
      - run:
          name: create config.yml
          command: ~/project/test/createConfigs.sh
      - store_artifacts:
          path: ~/artifacts
      - persist_to_workspace:
          root: ~/
          paths:
            - artifacts/

  test:
    docker:
      - image: circleci/circleci-cli:0.1.5879-alpine
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: validate configs
          command: ~/project/test/validateConfigs.sh

workflows:
  version: 2
  btd:
    jobs:
      - build
      - test:
          requires:
            - build

